Repository sillsdev/Glyssen, pull requests merged in 2019-11, with the labels that each got.

#550 PG-1276+ Prevent conflict between parser and ISP; Use undefined delivery when block has verses with conflicting deliveries
  ControlDataIntegrityTests/CharacterVerseDataTests.cs
  ControlDataIntegrityTests/ControlDataIntegrityTests.csproj
  ControlDataIntegrityTests/NarratorOverridesTests.cs
  Glyssen.sln.DotSettings
  Glyssen/App.config
  Glyssen/Block.cs
  Glyssen/Character/CharacterAssigner.cs
  Glyssen/Character/CharacterVerse.cs
  Glyssen/Character/CharacterVerseData.cs
  Glyssen/Character/CombinedCharacterVerseData.cs
  Glyssen/Character/ControlCharacterVerseData.cs
  Glyssen/Character/ICharacterVerseInfo.cs
  Glyssen/Character/ProjectCharacterVerseData.cs
  Glyssen/DataMigrator.cs
  Glyssen/Dialogs/AddCharacterDlg.cs
  Glyssen/Dialogs/AssignCharacterViewModel.cs
  Glyssen/Dialogs/BlockNavigatorViewModel.cs
  Glyssen/Glyssen.csproj
  Glyssen/Project.cs
  Glyssen/ProjectBase.cs
  Glyssen/ProjectDataMigrator.cs
  Glyssen/Properties/Settings.Designer.cs
  Glyssen/Properties/Settings.settings
  Glyssen/Quote/ParserCharacterRepository.cs
  Glyssen/Quote/QuoteParser.cs
  Glyssen/Quote/QuoteSystemGuesser.cs
  Glyssen/ReferenceText.cs
  Glyssen/Resources/CharacterVerse.txt
  Glyssen/Rules/CharacterGroupGenerator.cs
  Glyssen/Utilities/LinqExtensions.cs
  GlyssenShared/BlockElement.cs
  GlyssenTests/BlockTests.cs
  GlyssenTests/Character/CharacterAssignerTests.cs
  GlyssenTests/Character/CharacterVerseDataTests.cs
  GlyssenTests/Character/ProjectCharacterVerseDataTests.cs
  GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
  GlyssenTests/GlyssenTests.csproj
  GlyssenTests/ProjectDataMigratorTests.cs
  GlyssenTests/ProjectTests.cs
  GlyssenTests/Quote/QuoteParserTests.cs
  GlyssenTests/Quote/QuoteSystemGuesserTests.cs
  GlyssenTests/ReferenceTextTests.cs
  GlyssenTests/Resources/TestCharacterDetail.txt
  GlyssenTests/Resources/TestCharacterVerse.txt
  GlyssenTests/Resources/TestCharacterVerseOct2015.txt
  GlyssenTests/Rules/CharacterGroupsAdjusterTests.cs
  GlyssenTests/Utilities/VerseBridge.cs
  RefTextDevUtilities/ReferenceTextUtility.cs
Labels: enhancement

#552 PG-1285 Fix crash in NarratorOverrides when versification change causes chapter change in startRef
  ControlDataIntegrityTests/NarratorOverridesTests.cs
  Glyssen/Character/ControlCharacterVerseData.cs
  Glyssen/Character/NarratorOverrides.cs
  GlyssenTests/BookScriptTests.cs
  GlyssenTests/Character/CharacterVerseDataTests.cs
  GlyssenTests/Character/NarratorOverridesTests.cs
Labels: bug

#548 PG-1272: Interpret "wj" and "qt" character styles in usx parser
  DistFiles/sfm/usfm.sty
  Glyssen/Character/CharacterVerseData.cs
  Glyssen/Character/ControlCharacterVerseData.cs
  Glyssen/Quote/QuoteParser.cs
  Glyssen/UsxParser.cs
  GlyssenTests/Quote/QuoteParserTests.cs
  GlyssenTests/TestProject.cs
  GlyssenTests/UsxParserTests.cs
Labels: enhancement

#555 PG-1289: Prevented inconsistent state in TryLoadBlock
  Glyssen/BlockNavigator.cs
  Glyssen/Dialogs/BlockNavigatorViewModel.cs
  GlyssenTests/BlockNavigatorTests.cs
  GlyssenTests/Dialogs/BlockNavigatorViewModelTests.cs
Labels: bug

#556 PG-1279: Prevent index out of range in MatchVernBlocksToReferenceTextBlocks
  Glyssen/ReferenceText.cs
  GlyssenTests/ReferenceTextTests.cs
Labels: bug

#557 PG-1286, PG-1291: Fixed reference text joining code to clone before joining
  Glyssen/BookScript.cs
  Glyssen/ProjectDataMigrator.cs
  Glyssen/Resources/CharacterVerse.txt
  GlyssenTests/BookScriptTests.cs
  GlyssenTests/ProjectDataMigratorTests.cs
Labels: bug

#560 PG-1297: Prevent creation of a matchup that crosses a chapter boundary
  Glyssen/ReferenceText.cs
  GlyssenTests/ReferenceTextTests.cs
Labels: bug

#561 Convert GlyssenShared project to .NetStandard
  GlyssenShared/Bundle/GlyssenDblMetadataLanguage.cs
  GlyssenShared/GlyssenShared.csproj
  GlyssenShared/Properties/Settings.Designer.cs
  GlyssenShared/Properties/Settings.settings
Labels: work-in-progress

#558 PG-1290 Reworked the way we filter and display progress in rainbow mode
  Glyssen/BlockNavigator.cs
  Glyssen/BookBlockIndices.cs
  Glyssen/Controls/ScriptBlocksGridView.cs
  Glyssen/Dialogs/AssignCharacterDlg.cs
  Glyssen/Dialogs/AssignCharacterViewModel.cs
  Glyssen/Dialogs/BlockNavigatorViewModel.cs
  Glyssen/Dialogs/QuotationMarksDlg.cs
  Glyssen/IBlockAccessor.cs
  GlyssenTests/BlockNavigatorTests.cs
  GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs
  GlyssenTests/Dialogs/BlockNavigatorViewModelTests.cs
Labels: bug

#563 PG-1162: Processed PSA and fixed bugs in ReferenceTextUtility.
  DistFiles/reference_texts/English/PSA.xml
  Glyssen/Resources/CharacterDetail.txt
  Glyssen/Resources/CharacterVerse.txt
  RefTextDevUtilities/ReferenceTextUtility.cs
Labels: bug, enhancement

#565 Minor upgrade of PlatformAbstractions and Newtonsoft.Json
  ControlDataIntegrityTests/App.config
  ControlDataIntegrityTests/ControlDataIntegrityTests.csproj
  ControlDataIntegrityTests/packages.config
  DevTools/App.config
  DevTools/DevTools.csproj
  DevTools/packages.config
  Glyssen/App.config
  Glyssen/Glyssen.csproj
  Glyssen/packages.config
  GlyssenTests/App.config
  GlyssenTests/GlyssenTests.csproj
  GlyssenTests/packages.config
  RefTextDevUtilities/RefTextDevUtilities.csproj
  RefTextDevUtilities/app.config
  RefTextDevUtilities/packages.config
  Reference Text Utility/App.config
Labels: enhancement, low-priority
